# Generated by Django 3.0 on 2022-08-08 04:18

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
